import 'fake-indexeddb/auto';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import ts from 'typescript';
// Compile the production module without adding a second build system.
const source=ts.transpileModule(readFileSync(new URL('../lib/document-cache.ts',import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText;
const cache=await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64'));
let quota=1e12,usage=0;
Object.defineProperty(navigator,'storage',{value:{estimate:async()=>({quota,usage})}});
const sizes=[{width:600,height:800}];
const key=n=>cache.CACHE_VERSION+':'+n;
const tick=()=>new Promise(r=>setTimeout(r,4));
await cache.clearDocumentCache();
const a=new File(['abc'],'same.hwp',{lastModified:1}),b=new File(['xyz'],'same.hwp',{lastModified:1});
assert.notEqual(await cache.documentCacheKey(a),await cache.documentCacheKey(b));
assert.equal(await cache.documentCacheKey(a),await cache.documentCacheKey(new File(['abc'],'renamed.hwp')));
await cache.cacheDocument(key('a'),sizes);
await cache.cachePage(key('a'),0,'<svg>가나다</svg>');
assert.deepEqual(await cache.cachedDocument(key('a')),sizes);
assert.equal(await cache.cachedPage(key('a'),0),'<svg>가나다</svg>');
const before=await cache.cacheStats();
await cache.cachePage(key('a'),0,'<svg>가나다</svg>');
assert.equal((await cache.cacheStats()).bytes,before.bytes,'replacement must not double count');
await cache.clearDocumentCache();
await cache.cacheDocument(key('a'),sizes);await tick();
await cache.cacheDocument(key('b'),sizes);await tick();
await cache.cachedDocument(key('a'));await tick();
const two=(await cache.cacheStats()).bytes;
quota=(two+1)/0.9;
await cache.cacheDocument(key('c'),sizes);
assert.equal(await cache.cachedDocument(key('b')),undefined,'least recently used document evicted');
assert.ok(await cache.cachedDocument(key('a')));
assert.ok(await cache.cachedDocument(key('c')));
assert.ok((await cache.cacheStats()).bytes<=two+1);
await cache.cachePage(key('a'),0,'x'.repeat(10000));
assert.equal(await cache.cachedPage(key('a'),0),undefined,'oversize page skipped');
quota=1e12;
await cache.clearDocumentCache();
await Promise.all(Array.from({length:20},(_,i)=>cache.cacheDocument(key(i),sizes)));
assert.equal((await cache.cacheStats()).count,20,'concurrent writers preserve accounting');
await cache.cachePage(key(0),0,'<svg/>');
await cache.deleteCachedDocument(key(0));
assert.equal(await cache.cachedPage(key(0),0),undefined,'eviction deletes page blobs');
await cache.clearDocumentCache();
await cache.cachePage(key(1),0,'<svg/>');
assert.deepEqual(await cache.cacheStats(),{count:0,bytes:0},'pending page writes cannot resurrect cleared entries');
usage=cache.CACHE_LIMIT;
await cache.cacheDocument(key('no-space'),sizes);
assert.equal((await cache.cacheStats()).count,0,'saved originals / other storage reserve space');
usage=0;
// Account for multi-gigabyte entries without allocating 10 GB on the test machine.
await cache.clearDocumentCache();
const d=await new Promise((resolve,reject)=>{const r=indexedDB.open('hwp-grid-render-cache',1);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});
await new Promise((resolve,reject)=>{const tx=d.transaction('documents','readwrite');tx.objectStore('documents').put({id:key('large-old'),pages:sizes,bytes:6_000_000_000,lastUsed:1});tx.objectStore('documents').put({id:key('large-new'),pages:sizes,bytes:3_999_999_900,lastUsed:2});tx.oncomplete=resolve;tx.onabort=reject;});
await cache.cacheDocument(key('cross-10gb'),sizes);
assert.equal(await cache.cachedDocument(key('large-old')),undefined);
assert.ok((await cache.cacheStats()).bytes<=10_000_000_000,'10 GB hard ceiling');
await cache.clearDocumentCache();
await cache.cacheDocument('old-version:document',sizes);
await cache.cacheDocument(key('new-version'),sizes);
assert.equal(await cache.cachedDocument('old-version:document'),undefined);
await cache.clearDocumentCache();
console.log('PASS: content identity, reuse, replacement, LRU, size limit, concurrent writes, deletion, clear, storage reservation, version invalidation');
